### PR TITLE
Whitelist update + scamlist

### PR DESCRIPTION
**Pull request by Destiner**

### CODE REVIEW

**Comment by thegismar** [comment]
are you fucking kidding me?

**Comment by penandlim** [comment]
Do you guys test your commits?

**Comment by suspended** [comment]
So much for your BAL governance token. What a sham!

**Comment by maiaeos** [comment]
Set the yfii account free, pls.  give the power  back to users.pls. Give the justice back to community.pls. My mighty  king  lord of defi BAL

**Comment by thegismar** [comment]
> So much for your BAL governance token. What a sham!

which part of the TOS is this comment violating?

**Comment by jin10086** [comment]
> So much for your BAL governance token. What a sham!

which part of the TOS is this comment violating?

[What-is-a-TOS-violation](https://www.quora.com/What-is-a-TOS-violation)

**Comment by Creativenauts** [comment]
why is balancer not on this list?

**Comment by ghost** [comment]
> > So much for your BAL governance token. What a sham!
> 
> which part of the TOS is this comment violating?
> 
> [What-is-a-TOS-violation](https://www.quora.com/What-is-a-TOS-violation)

I can't tell if you're being funny or dull.

**Comment by jin10086** [comment]
> > > So much for your BAL governance token. What a sham!
> > 
> > 
> > which part of the TOS is this comment violating?
> > [What-is-a-TOS-violation](https://www.quora.com/What-is-a-TOS-violation)
> 
> I can't tell if you're being funny or dull.

I just care about him, not of funny or dull.

**Pull request merged**
